# Macaw - Code Editor
# Version: 1.0
# File: Settings

theme: system

font-family : Menlo
font-size   : 14
word-wrap   : false

indentation-char  : space
indentation-count : 4

syntax-default: swift
syntax-unknown: txt

# Syntax files for extensions

extensions:
    css             : css.default.yaml
    html            : html.default.yaml
    js              : js.default.yaml
    json            : json.default.yaml
    pbxproj         : swift.default.yaml
    plist           : xml.default.yaml
    storyboard      : xml.default.yaml
    swift           : swift.default.yaml
    xcbkptlist      : xml.default.yaml
    xcscheme        : xml.default.yaml
    xcworkspacedata : xml.default.yaml
    xml             : xml.default.yaml
    yaml            : yaml.default.yaml
    php             : php.default.yaml
# End
