# Macaw - Code Editor
# Version: 1.0
# File: Settings

#theme: dark

font-family : Menlo
font-size   : 14
word-wrap   : false

indentation-char  : space
indentation-count : 4

# Syntax templates

syntax-default         : swift
syntax-unknown         : txt
syntax-xml             : html
syntax-plist           : html
syntax-xcscheme        : html
syntax-pbxproj         : swift
syntax-xcbkptlist      : html
syntax-storyboard      : html
syntax-xcworkspacedata : html


# End
